version: '3.4'

services:
  luminapath:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=8001
      - ASPNETCORE_HTTPS_PORTS=8002
      - ConnectionStrings__Default=server=db;database=luminapath;user=root;password=dbuserpassword; 
    ports:
      - "7012:8001"
      - "7013:8002"
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/home/app/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/home/app/.aspnet/https:ro