version: '3.4'

services:
  luminapath:
    image: ${DOCKER_REGISTRY-}luminapath
    build:
      context: ../
      dockerfile: LuminaPath/Dockerfile
    environment:
        ConnectionStrings__Default: "server=db;database=luminapath;user=${MYSQL_USER};password=${MYSQL_PASSWORD};"
    depends_on:
        - db
  db:
     image: mysql:latest
     container_name: luminapath_DB
     environment:
       MYSQL_ROOT_PASSWORD: ${MYSQL_PASSWORD}
       MYSQL_DATABASE: luminapath
     volumes:
         - luminapath-DB:/var/lib/mysql
     expose:
         - "3306"
  blob:
    image: mcr.microsoft.com/azure-storage/azurite
    container_name: luminapath-blob
    volumes:
      - luminapath-blob:/data
    expose:
      - 10000

volumes:
    luminapath-DB:
    luminapath-blob: 
