services:
  luminapath:
    image: ${DOCKER_REGISTRY-}luminapath
    build:
      context: ../
      dockerfile: LuminaPath/Dockerfile
    environment:
      ConnectionStrings__Default: "Host=db;Port=5432;Database=luminapath;Username=${POSTGRES_USER};Password=${POSTGRES_PASSWORD};"
    depends_on:
      - db
  db:
    image: postgres:latest
    container_name: luminapath_DB
    environment:
      POSTGRES_DB: luminapath
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - luminapath-DB:/var/lib/postgresql
      - ./init:/docker-entrypoint-initdb.d
    ports:
      - "5432:5432"
  blob:
    image: mcr.microsoft.com/azure-storage/azurite
    container_name: luminapath-blob
    volumes:
      - luminapath-blob:/data
    expose:
      - 10000

volumes:
  luminapath-DB:
  luminapath-blob:
