services:
  luminapath:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=8001
      - ASPNETCORE_HTTPS_PORTS=8002
      - ConnectionStrings__Default=Host=db;Port=5432;Database=luminapath;Username=dev;Password=dbuserpassword;
    ports:
      - "7012:8001"
      - "7013:8002"
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/home/app/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/home/app/.aspnet/https:ro
  db:
    environment:
      POSTGRES_DB: luminapath
      POSTGRES_USER: dev
      POSTGRES_PASSWORD: dbuserpassword
