version: '3.4'

services:
  luminapath:
    image: ${DOCKER_REGISTRY-}luminapath
    container_name: luminapath
    build:
      context: .
      dockerfile: luminapath/Dockerfile  
    depends_on:
        - db
  db:
     image: mysql:latest
     container_name: luminapath_DB
     environment:
       MYSQL_ROOT_PASSWORD: dbuserpassword
       MYSQL_DATABASE: luminapath
     volumes:
         - luminapath-DB:/var/lib/mysql
     ports:
         - "3306:3306"
volumes:
    luminapath-DB:
