import { SkillTreeBranch, SkillTreeQuest } from '../models/skill-tree.model';

export const SKILL_TREE_BRANCHES: SkillTreeBranch[] = [
  {
    id: 'cooking',
    name: 'The Hearth',
    subtitle: 'Cooking',
    hue: 28,
    nodes: [
      { id: 'c1', name: 'Knife Skills', description: 'Dice an onion without tears.', position: [0, 0, 0], prereqIds: [], xp: 10 },
      { id: 'c2', name: 'Mise en Place', description: 'Prep before flame.', position: [-2.2, 1.4, 0.3], prereqIds: ['c1'], xp: 15 },
      { id: 'c3', name: 'Searing', description: 'Maillard mastery on cast iron.', position: [2.4, 1.0, -0.4], prereqIds: ['c1'], xp: 15 },
      { id: 'c4', name: 'Stocks & Broths', description: 'Coax bones into liquid gold.', position: [-3.6, 3.0, 0.6], prereqIds: ['c2'], xp: 20 },
      { id: 'c5', name: 'Sauces', description: 'The five mother sauces.', position: [-1.4, 3.4, -0.8], prereqIds: ['c2', 'c3'], xp: 25 },
      { id: 'c6', name: 'Roasting', description: 'Patience and a hot oven.', position: [3.8, 2.8, 0.2], prereqIds: ['c3'], xp: 20 },
      { id: 'c7', name: 'Baking Bread', description: 'Hydration, time, fire.', position: [-4.2, 5.2, -0.5], prereqIds: ['c4'], xp: 30 },
      { id: 'c8', name: 'Pastry', description: 'Cold butter, warm hands.', position: [-1.8, 5.6, 0.7], prereqIds: ['c5'], xp: 30 },
      { id: 'c9', name: 'Fermentation', description: 'Bubble, hiss, transform.', position: [1.2, 5.0, -0.6], prereqIds: ['c5'], xp: 30 },
      { id: 'c10', name: 'Smoking', description: 'Slow blue smoke.', position: [4.4, 4.6, -0.3], prereqIds: ['c6'], xp: 30 },
      { id: 'c11', name: 'Knife of the Master', description: 'Brunoise in your sleep.', position: [-2.8, 7.4, 0.0], prereqIds: ['c7', 'c8'], xp: 45 },
      { id: 'c12', name: 'Iron Stomach', description: 'Eat what you cook, fearlessly.', position: [2.6, 7.0, 0.3], prereqIds: ['c9', 'c10'], xp: 45 },
      { id: 'c13', name: 'Tasting Menu', description: 'Compose a 7-course progression.', position: [0, 8.6, 0], prereqIds: ['c11', 'c12'], xp: 60 },
      { id: 'c14', name: 'The Hearth Eternal', description: 'Feed others before yourself.', position: [0, 10.4, 0], prereqIds: ['c13'], xp: 100, capstone: true },
    ],
  },
  {
    id: 'programming',
    name: 'The Lattice',
    subtitle: 'Programming',
    hue: 200,
    nodes: [
      { id: 'p1', name: 'Variables', description: 'Name the unnamed.', position: [0, 0, 0], prereqIds: [], xp: 10 },
      { id: 'p2', name: 'Control Flow', description: 'Bend logic to your will.', position: [-2.4, 1.4, 0.4], prereqIds: ['p1'], xp: 15 },
      { id: 'p3', name: 'Functions', description: 'Compose, abstract, conquer.', position: [2.4, 1.4, -0.3], prereqIds: ['p1'], xp: 15 },
      { id: 'p4', name: 'Data Structures', description: 'Shape the formless.', position: [-3.8, 3.2, 0.0], prereqIds: ['p2'], xp: 20 },
      { id: 'p5', name: 'Recursion', description: 'See: Recursion.', position: [-1.2, 3.6, -0.6], prereqIds: ['p2', 'p3'], xp: 25 },
      { id: 'p6', name: 'Async Flows', description: 'Promises kept and broken.', position: [3.6, 3.0, 0.5], prereqIds: ['p3'], xp: 20 },
      { id: 'p7', name: 'Algorithms', description: 'O(n log n) or bust.', position: [-4.4, 5.4, -0.4], prereqIds: ['p4'], xp: 30 },
      { id: 'p8', name: 'Type Systems', description: 'Make illegal states unrepresentable.', position: [-1.6, 5.8, 0.6], prereqIds: ['p5'], xp: 30 },
      { id: 'p9', name: 'Concurrency', description: 'Race conditions, contained.', position: [1.4, 5.2, -0.5], prereqIds: ['p5', 'p6'], xp: 30 },
      { id: 'p10', name: 'Networking', description: 'Packets, protocols, latency.', position: [4.2, 4.8, 0.3], prereqIds: ['p6'], xp: 30 },
      { id: 'p11', name: 'Architecture', description: 'Boundaries that hold.', position: [-2.6, 7.4, 0.1], prereqIds: ['p7', 'p8'], xp: 45 },
      { id: 'p12', name: 'Distributed Systems', description: 'Eight fallacies, faced.', position: [2.8, 7.2, -0.2], prereqIds: ['p9', 'p10'], xp: 45 },
      { id: 'p13', name: 'Compilers', description: 'Build the tools that build.', position: [0, 8.8, 0.4], prereqIds: ['p11', 'p12'], xp: 60 },
      { id: 'p14', name: 'The Lattice Eternal', description: 'Code that outlives its author.', position: [0, 10.6, 0], prereqIds: ['p13'], xp: 100, capstone: true },
    ],
  },
  {
    id: 'drawing',
    name: 'The Mark',
    subtitle: 'Drawing',
    hue: 320,
    nodes: [
      { id: 'd1', name: 'The Line', description: 'A confident stroke.', position: [0, 0, 0], prereqIds: [], xp: 10 },
      { id: 'd2', name: 'Shape', description: 'Reduce the world to volumes.', position: [-2.2, 1.4, -0.4], prereqIds: ['d1'], xp: 15 },
      { id: 'd3', name: 'Value', description: 'Light, shadow, the spaces between.', position: [2.2, 1.4, 0.3], prereqIds: ['d1'], xp: 15 },
      { id: 'd4', name: 'Gesture', description: 'Capture motion in seconds.', position: [-3.6, 3.4, 0.3], prereqIds: ['d2'], xp: 20 },
      { id: 'd5', name: 'Anatomy', description: 'Bones, muscles, the figure.', position: [-1.0, 3.6, -0.7], prereqIds: ['d2', 'd3'], xp: 25 },
      { id: 'd6', name: 'Perspective', description: 'One point, two, three.', position: [3.6, 3.2, -0.4], prereqIds: ['d3'], xp: 20 },
      { id: 'd7', name: 'Composition', description: 'Where the eye should rest.', position: [-4.2, 5.4, 0.4], prereqIds: ['d4'], xp: 30 },
      { id: 'd8', name: 'Color Theory', description: 'Hue, value, chroma.', position: [-1.6, 5.8, -0.5], prereqIds: ['d5'], xp: 30 },
      { id: 'd9', name: 'Rendering', description: 'Surfaces that breathe.', position: [1.4, 5.2, 0.6], prereqIds: ['d5'], xp: 30 },
      { id: 'd10', name: 'Environment', description: 'Worlds with weather.', position: [4.2, 4.8, -0.3], prereqIds: ['d6'], xp: 30 },
      { id: 'd11', name: 'Style', description: 'A voice that is yours.', position: [-2.6, 7.4, 0.1], prereqIds: ['d7', 'd8'], xp: 45 },
      { id: 'd12', name: 'Storytelling', description: 'Pictures that mean things.', position: [2.8, 7.2, 0.4], prereqIds: ['d9', 'd10'], xp: 45 },
      { id: 'd13', name: 'The Sketchbook', description: 'A daily, lifelong practice.', position: [0, 8.8, -0.3], prereqIds: ['d11', 'd12'], xp: 60 },
      { id: 'd14', name: 'The Mark Eternal', description: 'Make something true.', position: [0, 10.6, 0], prereqIds: ['d13'], xp: 100, capstone: true },
    ],
  },
  {
    id: 'astronomy',
    name: 'The Vault',
    subtitle: 'Astronomy',
    hue: 260,
    nodes: [
      { id: 'a1', name: 'Naked Eye', description: 'Learn the brightest stars.', position: [0, 0, 0], prereqIds: [], xp: 10 },
      { id: 'a2', name: 'Constellations', description: 'Stories drawn in dots.', position: [-2.4, 1.4, 0.5], prereqIds: ['a1'], xp: 15 },
      { id: 'a3', name: 'Lunar Phases', description: "The moon's silver clock.", position: [2.4, 1.4, -0.4], prereqIds: ['a1'], xp: 15 },
      { id: 'a4', name: 'Planets', description: 'Wanderers among the fixed.', position: [-3.6, 3.2, 0.3], prereqIds: ['a2'], xp: 20 },
      { id: 'a5', name: 'Star Hopping', description: 'Find faint things from bright.', position: [-1.2, 3.6, -0.6], prereqIds: ['a2', 'a3'], xp: 25 },
      { id: 'a6', name: 'Telescope Craft', description: 'Collimate, focus, observe.', position: [3.6, 3.2, 0.4], prereqIds: ['a3'], xp: 20 },
      { id: 'a7', name: 'Deep Sky', description: 'Galaxies, nebulae, clusters.', position: [-4.2, 5.4, -0.4], prereqIds: ['a4'], xp: 30 },
      { id: 'a8', name: 'Astrophotography', description: 'Long exposures, longer patience.', position: [-1.6, 5.8, 0.5], prereqIds: ['a5'], xp: 30 },
      { id: 'a9', name: 'Spectroscopy', description: 'Read the light of stars.', position: [1.4, 5.2, -0.5], prereqIds: ['a5', 'a6'], xp: 30 },
      { id: 'a10', name: 'Orbital Mechanics', description: "Kepler's three laws.", position: [4.2, 4.8, 0.2], prereqIds: ['a6'], xp: 30 },
      { id: 'a11', name: 'Cosmology', description: "The universe's shape and age.", position: [-2.6, 7.4, 0.0], prereqIds: ['a7', 'a8'], xp: 45 },
      { id: 'a12', name: 'Stellar Evolution', description: 'Birth, fusion, collapse.', position: [2.8, 7.2, -0.3], prereqIds: ['a9', 'a10'], xp: 45 },
      { id: 'a13', name: 'Dark Sky Pilgrim', description: 'Travel for the Milky Way.', position: [0, 8.8, 0.5], prereqIds: ['a11', 'a12'], xp: 60 },
      { id: 'a14', name: 'The Vault Eternal', description: 'See yourself in the stars.', position: [0, 10.6, 0], prereqIds: ['a13'], xp: 100, capstone: true },
    ],
  },
  {
    id: 'swordsmanship',
    name: 'The Edge',
    subtitle: 'Swordsmanship',
    hue: 0,
    nodes: [
      { id: 's1', name: 'Stance', description: 'Roots before branches.', position: [0, 0, 0], prereqIds: [], xp: 10 },
      { id: 's2', name: 'Footwork', description: 'Distance is everything.', position: [-2.2, 1.4, -0.4], prereqIds: ['s1'], xp: 15 },
      { id: 's3', name: 'Cuts', description: 'Eight angles, one motion.', position: [2.2, 1.4, 0.3], prereqIds: ['s1'], xp: 15 },
      { id: 's4', name: 'Guards', description: 'Defense as preparation.', position: [-3.6, 3.2, 0.3], prereqIds: ['s2'], xp: 20 },
      { id: 's5', name: 'Parry', description: 'Redirect, never resist.', position: [-1.2, 3.6, -0.7], prereqIds: ['s2', 's3'], xp: 25 },
      { id: 's6', name: 'Riposte', description: 'The counter inside the cut.', position: [3.6, 3.2, -0.4], prereqIds: ['s3'], xp: 20 },
      { id: 's7', name: 'Binding', description: 'Feel through steel.', position: [-4.2, 5.4, 0.3], prereqIds: ['s4'], xp: 30 },
      { id: 's8', name: 'Voids', description: 'Strike where they are not.', position: [-1.6, 5.8, -0.4], prereqIds: ['s5'], xp: 30 },
      { id: 's9', name: 'Tempo', description: 'Own the rhythm of the fight.', position: [1.4, 5.2, 0.6], prereqIds: ['s5'], xp: 30 },
      { id: 's10', name: 'Half-Sword', description: 'Grip the blade, take the bind.', position: [4.2, 4.8, -0.3], prereqIds: ['s6'], xp: 30 },
      { id: 's11', name: 'Fechtbuch', description: 'Read the old masters.', position: [-2.6, 7.4, 0.1], prereqIds: ['s7', 's8'], xp: 45 },
      { id: 's12', name: 'Free Play', description: 'Spar without fear.', position: [2.8, 7.2, 0.4], prereqIds: ['s9', 's10'], xp: 45 },
      { id: 's13', name: 'Mushin', description: 'Mind of no-mind.', position: [0, 8.8, -0.3], prereqIds: ['s11', 's12'], xp: 60 },
      { id: 's14', name: 'The Edge Eternal', description: 'The sword that need not be drawn.', position: [0, 10.6, 0], prereqIds: ['s13'], xp: 100, capstone: true },
    ],
  },
];

export const SKILL_TREE_SEED_QUESTS: SkillTreeQuest[] = [
  { id: 'q-c1', branchId: 'cooking', text: 'Make stock from scratch', xp: 25, done: false },
  { id: 'q-c2', branchId: 'cooking', text: 'Bake a sourdough loaf', xp: 40, done: false },
  { id: 'q-c3', branchId: 'cooking', text: "Sharpen the chef's knife", xp: 10, done: true },
  { id: 'q-p1', branchId: 'programming', text: 'Refactor the auth module', xp: 30, done: false },
  { id: 'q-p2', branchId: 'programming', text: 'Write a recursive parser', xp: 35, done: false },
  { id: 'q-p3', branchId: 'programming', text: 'Read one chapter of SICP', xp: 20, done: false },
  { id: 'q-d1', branchId: 'drawing', text: '30-min figure session', xp: 25, done: false },
  { id: 'q-d2', branchId: 'drawing', text: 'Master study: Sargent', xp: 35, done: false },
  { id: 'q-d3', branchId: 'drawing', text: 'Fill a sketchbook page', xp: 15, done: true },
  { id: 'q-a1', branchId: 'astronomy', text: "Observe Jupiter's moons", xp: 30, done: false },
  { id: 'q-a2', branchId: 'astronomy', text: 'Identify 5 new constellations', xp: 25, done: false },
  { id: 'q-s1', branchId: 'swordsmanship', text: 'Drill 100 cuts (each side)', xp: 30, done: false },
  { id: 'q-s2', branchId: 'swordsmanship', text: 'Read Meyer Ch. 2', xp: 20, done: false },
];
