"""Refresh backend notices after a Release build (Python 3, no extra packages).

Uses package-bundled notices where available, otherwise retrieves the license
from the exact upstream repository commit recorded by NuGet. Review the result
before committing it; a successful download is not a license compatibility audit.
"""
import concurrent.futures
import json
from pathlib import Path
import urllib.error
import urllib.request
import xml.etree.ElementTree as ET

ROOT = Path(__file__).resolve().parents[1]
ASSETS = ROOT / "src/LuminaPath/obj/project.assets.json"
DEPS = ROOT / "src/LuminaPath/bin/Release/net10.0/LuminaPath.deps.json"
OUTPUT = ROOT / "licenses"
CACHE = ROOT / "artifacts/license-downloads"


def download(url):
    import hashlib
    path = CACHE / hashlib.sha256(url.encode()).hexdigest()
    if path.exists():
        return path.read_text(encoding="utf-8")
    try:
        with urllib.request.urlopen(url, timeout=30) as response:
            text = response.read().decode("utf-8-sig")
    except urllib.error.HTTPError as error:
        if error.code == 404:
            return None
        raise
    path.write_text(text, encoding="utf-8")
    return text


def collect(item, folders):
    identity, info = item
    folder = next((Path(base) / info["path"] for base in folders if (Path(base) / info["path"]).is_dir()), None)
    if folder is None:
        raise ValueError(f"Restore {identity} before generating notices")
    metadata = ET.parse(next(folder.glob("*.nuspec")))
    fields = {element.tag.split("}")[-1]: element for element in metadata.iter()}
    license_node = fields.get("license")
    expression = license_node.text if license_node is not None else "See upstream license"
    bundled = [p for p in folder.iterdir() if p.is_file() and any(word in p.name.lower() for word in ("license", "notice", "copying", "copyright")) and p.suffix not in (".nupkg", ".sha512")]
    if license_node is not None and license_node.attrib.get("type") == "file":
        declared = folder / license_node.text
        if declared not in bundled:
            bundled.append(declared)
    texts = [(p.name, p.read_text(encoding="utf-8-sig")) for p in sorted(bundled)]
    upstream = fields.get("repository")
    if not any("license" in name.lower() or "copying" in name.lower() for name, _ in texts):
        if upstream is not None and upstream.attrib.get("commit"):
            repo = upstream.attrib["url"].rstrip("/").removesuffix(".git")
            commit = upstream.attrib["commit"]
        elif identity == "ExcelNumberFormat/1.1.0":
            repo, commit = "https://github.com/andersnm/ExcelNumberFormat", "v1.1.0"
        else:
            raise ValueError(f"No bundled license or pinned repository for {identity}")
        if not repo.startswith("https://github.com/"):
            raise ValueError(f"Review upstream license source for {identity}: {repo}")
        base = repo.replace("https://github.com/", "https://raw.githubusercontent.com/") + f"/{commit}/"
        for name in ("LICENSE", "LICENSE.txt", "LICENSE.md", "license.txt", "License.txt", "LICENSE.TXT", "License.md", "LICENSE-MIT"):
            text = download(base + name)
            if text:
                texts.append((base + name, text))
                break
        else:
            raise ValueError(f"No license found at {base} for {identity}")
        for name in ("NOTICE", "NOTICE.txt", "THIRD-PARTY-NOTICES.TXT", "ThirdPartyNotices.txt"):
            text = download(base + name)
            if text:
                texts.append((base + name, text))
    notice = f"{'=' * 78}\n{identity}\nDeclared license: {expression}\n"
    for name, text in texts:
        notice += f"\nSource: {name}\n\n{text.rstrip()}\n"
    return identity, notice


def main():
    assets = json.loads(ASSETS.read_text(encoding="utf-8-sig"))
    deps = json.loads(DEPS.read_text(encoding="utf-8-sig"))
    shipped = {key for key, value in deps["libraries"].items() if value["type"] == "package"}
    items = sorted((key, value) for key, value in assets["libraries"].items() if key in shipped)
    OUTPUT.mkdir(exist_ok=True)
    CACHE.mkdir(parents=True, exist_ok=True)
    with concurrent.futures.ThreadPoolExecutor(max_workers=6) as pool:
        results = list(pool.map(lambda item: collect(item, assets["packageFolders"]), items))
    (OUTPUT / "backend.txt").write_text(
        "LuminaPath backend dependency licenses\nGenerated by scripts/update-backend-licenses.py\n\n"
        + "\n".join(text for _, text in results), encoding="utf-8")
    (OUTPUT / "backend-packages.json").write_text(json.dumps([identity for identity, _ in results], indent=2) + "\n", encoding="utf-8")
    print(f"Collected notices for {len(results)} backend packages")


if __name__ == "__main__":
    main()
