<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UserSecretsId>fabbbd6d-fa9d-4353-b58b-557585e6af29</UserSecretsId>
    <DockerDefaultTargetOS>Linux</DockerDefaultTargetOS>
    <DockerComposeProjectPath>..\docker-compose.dcproj</DockerComposeProjectPath>
    <DockerfileContext>..\..</DockerfileContext>
    <DockerfileTag>luminapath-server</DockerfileTag>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="Entities\**" />
    <Content Remove="Entities\**" />
    <EmbeddedResource Remove="Entities\**" />
    <None Remove="Entities\**" />
  </ItemGroup>

  <ItemGroup>
    <None Include="Pages\Admin\Users\Components\UserForm.razor" />
    <None Include="Pages\Admin\Users\Components\UserFormDialog.razor" />
    <None Include="Pages\Admin\Users\Users.razor" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.SpaProxy" Version="9.0.0" />
    <PackageReference Include="Microsoft.AspNetCore.SpaServices.Extensions" Version="9.0.0" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="9.0.0">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="Microsoft.VisualStudio.Azure.Containers.Tools.Targets" Version="1.21.0" />
    <PackageReference Include="MudBlazor" Version="7.15.0" />
    <PackageReference Include="Radzen.Blazor" Version="5.7.2" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\LuminaPath.Core\LuminaPath.Core.csproj" />
    <ProjectReference Include="..\LuminaPath.Infrastructure\LuminaPath.Infrastructure.csproj" />
  </ItemGroup>

</Project>
