<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <BlazorDisableThrowNavigationException>true</BlazorDisableThrowNavigationException>
    <UserSecretsId>fabbbd6d-fa9d-4353-b58b-557585e6af29</UserSecretsId>
    <DockerDefaultTargetOS>Linux</DockerDefaultTargetOS>
    <DockerfileContext>..\..</DockerfileContext>
    <DockerfileTag>luminapath-server</DockerfileTag>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="Entities\**" />
    <Content Remove="Entities\**" />
    <EmbeddedResource Remove="Entities\**" />
    <None Remove="Entities\**" />
  </ItemGroup>

  <ItemGroup>
    <None Include="Features\Admin\Users\Components\UserForm.razor" />
    <None Include="Features\Admin\Users\Components\UserFormDialog.razor" />
    <None Include="Features\Admin\Users\Users.razor" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="Microsoft.VisualStudio.Azure.Containers.Tools.Targets" />
    <PackageReference Include="MudBlazor" />
    <PackageReference Include="QRCoder" />
    <PackageReference Include="Radzen.Blazor" />
    <PackageReference Include="Serilog.AspNetCore" />
    <PackageReference Include="Serilog.Sinks.File" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\LuminaPath.Core\LuminaPath.Core.csproj" />
    <ProjectReference Include="..\LuminaPath.Infrastructure\LuminaPath.Infrastructure.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="App_Data\storage\" />
  </ItemGroup>

  <ItemGroup>
    <Content Include="../../LICENSE" Link="wwwroot/legal/LICENSE.txt" CopyToOutputDirectory="PreserveNewest" CopyToPublishDirectory="PreserveNewest" />
    <Content Include="../../THIRD_PARTY_NOTICES.md" Link="wwwroot/legal/THIRD_PARTY_NOTICES.txt" CopyToOutputDirectory="PreserveNewest" CopyToPublishDirectory="PreserveNewest" />
    <Content Include="../../legal/**/*" Link="wwwroot/legal/%(RecursiveDir)%(Filename)%(Extension)" CopyToOutputDirectory="PreserveNewest" CopyToPublishDirectory="PreserveNewest" />
    <Content Include="../../licenses/**/*" Link="wwwroot/legal/licenses/%(RecursiveDir)%(Filename)%(Extension)" CopyToOutputDirectory="PreserveNewest" CopyToPublishDirectory="PreserveNewest" />
  </ItemGroup>

</Project>
