// <auto-generated />
using System;
using System.Collections.Generic;
using LuminaPath.Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace LuminaPath.Infrastructure.Migrations
{
    [DbContext(typeof(LuminaPathDbContext))]
    [Migration("20260516130318_MyGamesPersonalNotes")]
    partial class MyGamesPersonalNotes
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("LuminaPath.Core.Models.Achievement", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<int>("QuestProfileId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("UnlockedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("QuestProfileId", "Code")
                        .IsUnique();

                    b.ToTable("Achievements");
                });

            modelBuilder.Entity("LuminaPath.Core.Models.ApplicationSetting", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Key")
                        .IsUnique();

                    b.ToTable("ApplicationSettings");
                });

            modelBuilder.Entity("LuminaPath.Core.Models.Base.Document", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ContentType")
                        .HasColumnType("text");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasMaxLength(13)
                        .HasColumnType("character varying(13)");

                    b.Property<int>("DocumentType")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<string>("Path")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Documents");

                    b.HasDiscriminator<string>("Discriminator").HasValue("Document");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("LuminaPath.Core.Models.Base.Media", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("character varying(8)");

                    b.PrimitiveCollection<List<string>>("Genres")
                        .IsRequired()
                        .HasColumnType("text[]");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime?>("ReleaseDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Media");

                    b.HasDiscriminator<string>("Discriminator").HasValue("Media");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("LuminaPath.Core.Models.DirectMessage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("ReadAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("RecipientId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("SenderId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("SentAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("RecipientId");

                    b.HasIndex("SenderId", "RecipientId", "SentAt");

                    b.ToTable("DirectMessages");
                });

            modelBuilder.Entity("LuminaPath.Core.Models.Friendship", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("AddresseeId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("RequesterId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("RespondedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("AddresseeId");

                    b.HasIndex("RequesterId", "AddresseeId")
                        .IsUnique();

                    b.ToTable("Friendships");
                });

            modelBuilder.Entity("LuminaPath.Core.Models.GamingSession", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("Completed")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("DurationMinutes")
                        .HasColumnType("integer");

                    b.Property<string>("LuminaUserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("MyGameId")
                        .HasColumnType("integer");

                    b.Property<string>("Notes")
                        .HasColumnType("text");

                    b.Property<DateTime>("ScheduledAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("MyGameId");

                    b.HasIndex("LuminaUserId", "ScheduledAt");

                    b.ToTable("GamingSessions");
                });

            modelBuilder.Entity("LuminaPath.Core.Models.MediaExternalId", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ExternalId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<int>("MediaId")
                        .HasColumnType("integer");

                    b.Property<int>("Provider")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("MediaId");

                    b.HasIndex("Provider", "ExternalId")
                        .IsUnique();

                    b.ToTable("MediaExternalIds");
                });

            modelBuilder.Entity("LuminaPath.Core.Models.MyAnime", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("AnimeId")
                        .HasColumnType("integer");

                    b.Property<int?>("CurrentEpisode")
                        .HasColumnType("integer");

                    b.Property<int?>("CurrentWatchTimeMinutes")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("EndDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("LuminaUserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Priority")
                        .HasColumnType("integer");

                    b.Property<short?>("Rating")
                        .HasColumnType("smallint");

                    b.Property<DateTime?>("StartDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<double?>("TimeSpend")
                        .HasColumnType("double precision");

                    b.HasKey("Id");

                    b.HasIndex("AnimeId");

                    b.HasIndex("LuminaUserId");

                    b.ToTable("MyAnimes");
                });

            modelBuilder.Entity("LuminaPath.Core.Models.MyGame", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("EndDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("GameId")
                        .HasColumnType("integer");

                    b.Property<string>("LuminaUserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PersonalNotes")
                        .HasColumnType("text");

                    b.Property<int>("Priority")
                        .HasColumnType("integer");

                    b.Property<short?>("Rating")
                        .HasColumnType("smallint");

                    b.Property<DateTime?>("StartDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<double?>("TimeSpend")
                        .HasColumnType("double precision");

                    b.HasKey("Id");

                    b.HasIndex("GameId");

                    b.HasIndex("LuminaUserId");

                    b.ToTable("MyGames");
                });

            modelBuilder.Entity("LuminaPath.Core.Models.MyMovie", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("CurrentWatchTimeMinutes")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("EndDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("LuminaUserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("MovieId")
                        .HasColumnType("integer");

                    b.Property<int>("Priority")
                        .HasColumnType("integer");

                    b.Property<short?>("Rating")
                        .HasColumnType("smallint");

                    b.Property<DateTime?>("StartDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<double?>("TimeSpend")
                        .HasColumnType("double precision");

                    b.HasKey("Id");

                    b.HasIndex("LuminaUserId");

                    b.HasIndex("MovieId");

                    b.ToTable("MyMovies");
                });

            modelBuilder.Entity("LuminaPath.Core.Models.MySeries", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("CurrentEpisode")
                        .HasColumnType("integer");

                    b.Property<int?>("CurrentWatchTimeMinutes")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("EndDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("LuminaUserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Priority")
                        .HasColumnType("integer");

                    b.Property<short?>("Rating")
                        .HasColumnType("smallint");

                    b.Property<int>("SeriesId")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("StartDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<double?>("TimeSpend")
                        .HasColumnType("double precision");

                    b.HasKey("Id");

                    b.HasIndex("LuminaUserId");

                    b.HasIndex("SeriesId");

                    b.ToTable("MySeries");
                });

            modelBuilder.Entity("LuminaPath.Core.Models.Quest", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("Completed")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("DueDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("LuminaUserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("MyGameId")
                        .HasColumnType("integer");

                    b.Property<string>("Notes")
                        .HasColumnType("text");

                    b.Property<int>("Priority")
                        .HasColumnType("integer");

                    b.Property<int>("Recurrence")
                        .HasColumnType("integer");

                    b.Property<int>("RewardXp")
                        .HasColumnType("integer");

                    b.Property<int?>("SkillId")
                        .HasColumnType("integer");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer");

                    b.Property<string>("Tags")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("jsonb")
                        .HasDefaultValueSql("'[]'::jsonb");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Type")
                        .HasColumnType("integer");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("MyGameId");

                    b.HasIndex("SkillId");

                    b.HasIndex("LuminaUserId", "SortOrder");

                    b.HasIndex("LuminaUserId", "Completed", "DueDate");

                    b.ToTable("Quests");
                });

            modelBuilder.Entity("LuminaPath.Core.Models.QuestProfile", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("CurrentStreakDays")
                        .HasColumnType("integer");

                    b.Property<DateOnly?>("LastCompletionDate")
                        .HasColumnType("date");

                    b.Property<int>("LongestStreakDays")
                        .HasColumnType("integer");

                    b.Property<string>("LuminaUserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("TotalXp")
                        .HasColumnType("integer");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("LuminaUserId")
                        .IsUnique();

                    b.ToTable("QuestProfiles");
                });

            modelBuilder.Entity("LuminaPath.Core.Models.QuestSkill", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Color")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Icon")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("LuminaUserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer");

                    b.Property<int>("Xp")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("LuminaUserId");

                    b.ToTable("QuestSkills");
                });

            modelBuilder.Entity("LuminaPath.Core.Models.QuestSkillNode", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("QuestSkillId")
                        .HasColumnType("integer");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer");

                    b.Property<bool>("Unlocked")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("UnlockedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("QuestSkillId");

                    b.ToTable("QuestSkillNodes");
                });

            modelBuilder.Entity("LuminaPath.Core.Models.QuestSubtask", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("Completed")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("QuestId")
                        .HasColumnType("integer");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("QuestId", "SortOrder");

                    b.ToTable("QuestSubtasks");
                });

            modelBuilder.Entity("LuminaPath.Core.Models.Third_Party.LuminaUserInfo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("PSNAccountId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("PSNBronze")
                        .HasColumnType("integer");

                    b.Property<int>("PSNGold")
                        .HasColumnType("integer");

                    b.Property<string>("PSNOnlineId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("PSNPlatinum")
                        .HasColumnType("integer");

                    b.Property<int>("PSNSilver")
                        .HasColumnType("integer");

                    b.Property<int>("PSNTrophyLevel")
                        .HasColumnType("integer");

                    b.Property<string>("SteamAvatarUrl")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("SteamId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("SteamPersonaName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("SteamProfileUrl")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("LuminaUserInfo");
                });

            modelBuilder.Entity("LuminaPath.Core.Models.Third_Party.MyGameInfo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("FirstPlayed")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("LastPlayed")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("MyGameId")
                        .HasColumnType("integer");

                    b.Property<double>("TrackedHours")
                        .HasColumnType("double precision");

                    b.HasKey("Id");

                    b.HasIndex("MyGameId")
                        .IsUnique();

                    b.ToTable("MyGameInfo");
                });

            modelBuilder.Entity("LuminaPath.Infrastructure.Identity.LuminaUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("integer");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("boolean");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("text");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("text");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("boolean");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("text");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("boolean");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("text");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("text");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("text");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("text");

                    b.Property<string>("RoleId")
                        .HasColumnType("text");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("text");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<string>("Value")
                        .HasColumnType("text");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("LuminaPath.Core.Models.MediaDocument", b =>
                {
                    b.HasBaseType("LuminaPath.Core.Models.Base.Document");

                    b.Property<int?>("MediaId")
                        .HasColumnType("integer");

                    b.HasIndex("MediaId")
                        .IsUnique();

                    b.HasDiscriminator().HasValue("MediaDocument");
                });

            modelBuilder.Entity("LuminaPath.Core.Models.UserDocument", b =>
                {
                    b.HasBaseType("LuminaPath.Core.Models.Base.Document");

                    b.Property<string>("Album")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasIndex("UserId");

                    b.HasDiscriminator().HasValue("UserDocument");
                });

            modelBuilder.Entity("LuminaPath.Core.Models.Anime", b =>
                {
                    b.HasBaseType("LuminaPath.Core.Models.Base.Media");

                    b.Property<int?>("EpisodeCount")
                        .HasColumnType("integer");

                    b.Property<int?>("ExpectedWatchTimePerEpisodeMinutes")
                        .HasColumnType("integer");

                    b.Property<int?>("ParentAnimeId")
                        .HasColumnType("integer");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.HasIndex("ParentAnimeId");

                    b.HasDiscriminator().HasValue("Anime");
                });

            modelBuilder.Entity("LuminaPath.Core.Models.Game", b =>
                {
                    b.HasBaseType("LuminaPath.Core.Models.Base.Media");

                    b.Property<int?>("ParentGameId")
                        .HasColumnType("integer");

                    b.Property<int>("Platforms")
                        .HasColumnType("integer");

                    b.Property<int?>("Playtime")
                        .HasColumnType("integer");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.HasIndex("ParentGameId");

                    b.HasDiscriminator().HasValue("Game");
                });

            modelBuilder.Entity("LuminaPath.Core.Models.Movie", b =>
                {
                    b.HasBaseType("LuminaPath.Core.Models.Base.Media");

                    b.Property<int?>("ExpectedWatchTimeMinutes")
                        .HasColumnType("integer");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.HasDiscriminator().HasValue("Movie");
                });

            modelBuilder.Entity("LuminaPath.Core.Models.Series", b =>
                {
                    b.HasBaseType("LuminaPath.Core.Models.Base.Media");

                    b.Property<int?>("EpisodeCount")
                        .HasColumnType("integer");

                    b.Property<int?>("ExpectedWatchTimePerEpisodeMinutes")
                        .HasColumnType("integer");

                    b.Property<int?>("ParentSeriesId")
                        .HasColumnType("integer");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.HasIndex("ParentSeriesId");

                    b.ToTable("Media", t =>
                        {
                            t.Property("EpisodeCount")
                                .HasColumnName("Series_EpisodeCount");

                            t.Property("ExpectedWatchTimePerEpisodeMinutes")
                                .HasColumnName("Series_ExpectedWatchTimePerEpisodeMinutes");
                        });

                    b.HasDiscriminator().HasValue("Series");
                });

            modelBuilder.Entity("LuminaPath.Core.Models.Achievement", b =>
                {
                    b.HasOne("LuminaPath.Core.Models.QuestProfile", "QuestProfile")
                        .WithMany("Achievements")
                        .HasForeignKey("QuestProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("QuestProfile");
                });

            modelBuilder.Entity("LuminaPath.Core.Models.DirectMessage", b =>
                {
                    b.HasOne("LuminaPath.Infrastructure.Identity.LuminaUser", null)
                        .WithMany()
                        .HasForeignKey("RecipientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LuminaPath.Infrastructure.Identity.LuminaUser", null)
                        .WithMany()
                        .HasForeignKey("SenderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("LuminaPath.Core.Models.Friendship", b =>
                {
                    b.HasOne("LuminaPath.Infrastructure.Identity.LuminaUser", null)
                        .WithMany()
                        .HasForeignKey("AddresseeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LuminaPath.Infrastructure.Identity.LuminaUser", null)
                        .WithMany()
                        .HasForeignKey("RequesterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("LuminaPath.Core.Models.GamingSession", b =>
                {
                    b.HasOne("LuminaPath.Infrastructure.Identity.LuminaUser", null)
                        .WithMany()
                        .HasForeignKey("LuminaUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LuminaPath.Core.Models.MyGame", "MyGame")
                        .WithMany("GamingSessions")
                        .HasForeignKey("MyGameId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("MyGame");
                });

            modelBuilder.Entity("LuminaPath.Core.Models.MediaExternalId", b =>
                {
                    b.HasOne("LuminaPath.Core.Models.Base.Media", "Media")
                        .WithMany("ExternalIds")
                        .HasForeignKey("MediaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Media");
                });

            modelBuilder.Entity("LuminaPath.Core.Models.MyAnime", b =>
                {
                    b.HasOne("LuminaPath.Core.Models.Anime", "Anime")
                        .WithMany("MyAnimes")
                        .HasForeignKey("AnimeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LuminaPath.Infrastructure.Identity.LuminaUser", null)
                        .WithMany()
                        .HasForeignKey("LuminaUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Anime");
                });

            modelBuilder.Entity("LuminaPath.Core.Models.MyGame", b =>
                {
                    b.HasOne("LuminaPath.Core.Models.Game", "Game")
                        .WithMany("MyGames")
                        .HasForeignKey("GameId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LuminaPath.Infrastructure.Identity.LuminaUser", null)
                        .WithMany("MyGames")
                        .HasForeignKey("LuminaUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Game");
                });

            modelBuilder.Entity("LuminaPath.Core.Models.MyMovie", b =>
                {
                    b.HasOne("LuminaPath.Infrastructure.Identity.LuminaUser", null)
                        .WithMany()
                        .HasForeignKey("LuminaUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LuminaPath.Core.Models.Movie", "Movie")
                        .WithMany("MyMovies")
                        .HasForeignKey("MovieId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Movie");
                });

            modelBuilder.Entity("LuminaPath.Core.Models.MySeries", b =>
                {
                    b.HasOne("LuminaPath.Infrastructure.Identity.LuminaUser", null)
                        .WithMany()
                        .HasForeignKey("LuminaUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LuminaPath.Core.Models.Series", "Series")
                        .WithMany("MySeries")
                        .HasForeignKey("SeriesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Series");
                });

            modelBuilder.Entity("LuminaPath.Core.Models.Quest", b =>
                {
                    b.HasOne("LuminaPath.Infrastructure.Identity.LuminaUser", null)
                        .WithMany()
                        .HasForeignKey("LuminaUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LuminaPath.Core.Models.MyGame", "MyGame")
                        .WithMany("Quests")
                        .HasForeignKey("MyGameId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("LuminaPath.Core.Models.QuestSkill", "Skill")
                        .WithMany()
                        .HasForeignKey("SkillId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("MyGame");

                    b.Navigation("Skill");
                });

            modelBuilder.Entity("LuminaPath.Core.Models.QuestProfile", b =>
                {
                    b.HasOne("LuminaPath.Infrastructure.Identity.LuminaUser", null)
                        .WithMany()
                        .HasForeignKey("LuminaUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("LuminaPath.Core.Models.QuestSkill", b =>
                {
                    b.HasOne("LuminaPath.Infrastructure.Identity.LuminaUser", null)
                        .WithMany()
                        .HasForeignKey("LuminaUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("LuminaPath.Core.Models.QuestSkillNode", b =>
                {
                    b.HasOne("LuminaPath.Core.Models.QuestSkill", "QuestSkill")
                        .WithMany("Nodes")
                        .HasForeignKey("QuestSkillId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("QuestSkill");
                });

            modelBuilder.Entity("LuminaPath.Core.Models.QuestSubtask", b =>
                {
                    b.HasOne("LuminaPath.Core.Models.Quest", "Quest")
                        .WithMany("Subtasks")
                        .HasForeignKey("QuestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Quest");
                });

            modelBuilder.Entity("LuminaPath.Core.Models.Third_Party.LuminaUserInfo", b =>
                {
                    b.HasOne("LuminaPath.Infrastructure.Identity.LuminaUser", null)
                        .WithOne("LuminaUserInfo")
                        .HasForeignKey("LuminaPath.Core.Models.Third_Party.LuminaUserInfo", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("LuminaPath.Core.Models.Third_Party.MyGameInfo", b =>
                {
                    b.HasOne("LuminaPath.Core.Models.MyGame", "Game")
                        .WithOne("MyGameInfo")
                        .HasForeignKey("LuminaPath.Core.Models.Third_Party.MyGameInfo", "MyGameId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Game");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("LuminaPath.Infrastructure.Identity.LuminaUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("LuminaPath.Infrastructure.Identity.LuminaUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LuminaPath.Infrastructure.Identity.LuminaUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("LuminaPath.Infrastructure.Identity.LuminaUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("LuminaPath.Core.Models.MediaDocument", b =>
                {
                    b.HasOne("LuminaPath.Core.Models.Base.Media", "Media")
                        .WithOne("Image")
                        .HasForeignKey("LuminaPath.Core.Models.MediaDocument", "MediaId");

                    b.Navigation("Media");
                });

            modelBuilder.Entity("LuminaPath.Core.Models.UserDocument", b =>
                {
                    b.HasOne("LuminaPath.Infrastructure.Identity.LuminaUser", null)
                        .WithMany("Documents")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("LuminaPath.Core.Models.Anime", b =>
                {
                    b.HasOne("LuminaPath.Core.Models.Anime", "ParentAnime")
                        .WithMany("Seasons")
                        .HasForeignKey("ParentAnimeId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("ParentAnime");
                });

            modelBuilder.Entity("LuminaPath.Core.Models.Game", b =>
                {
                    b.HasOne("LuminaPath.Core.Models.Game", "ParentGame")
                        .WithMany("Dlcs")
                        .HasForeignKey("ParentGameId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("ParentGame");
                });

            modelBuilder.Entity("LuminaPath.Core.Models.Series", b =>
                {
                    b.HasOne("LuminaPath.Core.Models.Series", "ParentSeries")
                        .WithMany("Seasons")
                        .HasForeignKey("ParentSeriesId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("ParentSeries");
                });

            modelBuilder.Entity("LuminaPath.Core.Models.Base.Media", b =>
                {
                    b.Navigation("ExternalIds");

                    b.Navigation("Image");
                });

            modelBuilder.Entity("LuminaPath.Core.Models.MyGame", b =>
                {
                    b.Navigation("GamingSessions");

                    b.Navigation("MyGameInfo");

                    b.Navigation("Quests");
                });

            modelBuilder.Entity("LuminaPath.Core.Models.Quest", b =>
                {
                    b.Navigation("Subtasks");
                });

            modelBuilder.Entity("LuminaPath.Core.Models.QuestProfile", b =>
                {
                    b.Navigation("Achievements");
                });

            modelBuilder.Entity("LuminaPath.Core.Models.QuestSkill", b =>
                {
                    b.Navigation("Nodes");
                });

            modelBuilder.Entity("LuminaPath.Infrastructure.Identity.LuminaUser", b =>
                {
                    b.Navigation("Documents");

                    b.Navigation("LuminaUserInfo");

                    b.Navigation("MyGames");
                });

            modelBuilder.Entity("LuminaPath.Core.Models.Anime", b =>
                {
                    b.Navigation("MyAnimes");

                    b.Navigation("Seasons");
                });

            modelBuilder.Entity("LuminaPath.Core.Models.Game", b =>
                {
                    b.Navigation("Dlcs");

                    b.Navigation("MyGames");
                });

            modelBuilder.Entity("LuminaPath.Core.Models.Movie", b =>
                {
                    b.Navigation("MyMovies");
                });

            modelBuilder.Entity("LuminaPath.Core.Models.Series", b =>
                {
                    b.Navigation("MySeries");

                    b.Navigation("Seasons");
                });
#pragma warning restore 612, 618
        }
    }
}
